import Head from 'next/head';
import Link from 'next/link';
import React from 'react';

import styles from '../styles/layout.module.css'

export default function Layout({ children }) {
    return (
        <div>
            <Head>
                <title>Create Next App</title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <nav className={styles.container}>
                <Link href={'/'}>
                <a>
                    Home | 
                </a>
                </Link>
                <Link href={'/proyectos'}>
                    <a>
                        Proyectos |
                    </a>
                </Link>
                <Link href={'/about'}>
                    <a>
                        About me |
                    </a>
                </Link>
                <Link href={'/blog'}>
                    <a>
                        Blog
                    </a>
                </Link>
            </nav>

            {children}

        </div>
    );
};

